# This is a basic workflow to help you get started with Actions
# It triggers on each push to the main branch and sets up AIO CLI using "AIO CLI Setup - Action" and then installs the plugin for cloud manager on top of the existing CLI.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.1.0
        with:
          os: ubuntu-latest
          version: 7.0.0
      - run: aio plugins:install @adobe/aio-cli-plugin-cloudmanager
