# This is a basic workflow to help you get started with Actions
# It triggers on each push to the main branch and sets up AIO CLI using "AIO CLI Setup - Action" and then installs the plugin for cloud manager on top of the existing CLI.
on: 
 workflow_dispatch:
  inputs:
   env:
    description: 'Env Name'
    default: 'dev'
    type: cjoice
    options:
    - dev
    - sit
    - stage
    - prod
    
jobs:
  Configure-Adobe-IO:
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.1.0
      
      - name: Install CM plugin
        run: aio plugins:install @adobe/aio-cli-plugin-cloudmanager
      
      - name: Configure Authentication
        run: |
           aio config:set ims.contexts.aio-cli-plugin-cloudmanager config.json --file --json
           aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key private.key --file
           echo You Selected ${{ inputs.env }}
           
