name: Trigger Build

#This workflow executes, whenever there is a pull request to develop branch.
# it will sync the code and trigger the pipeline in CM

on: push

jobs:      
  Checkout:
    runs-on: ubuntu-latest
    steps:    
     - name: Checkout
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0
   
  Code-Sync-Dev: 
        if: github.ref == 'refs/heads/develop'
        runs-on: ubuntu-latest
        needs: Checkout
        steps:  
         - name: Code Sync to develop branch
           run: |
             sudo apt-get install -y unzip git
             git remote add poc https://github.com/Vranda1188/AEM-Remote.git
             git config credential.username ${{ secrets.GIT_USER }}
             git config credential.helper ${{ secrets.GIT_PAT }}
             git remote -v
             git checkout develop
             git pull
             git push -f -u poc develop
           shell: bash
         
         - name: Storybook
           run: echo "This will update the child repo"
       
  Code-Sync-Main:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: Checkout
        steps:    
         - name: Code Sync to main branch
           run: |
             sudo apt-get install -y unzip git
             git remote add poc https://github.com/Vranda1188/AEM-Remote.git
             git config credential.username ${{ secrets.GIT_USER }}
             git config credential.helper ${{ secrets.GIT_PAT }}
             git remote -v
             git checkout main
             git pull
             git push -f -u poc main
           shell: bash
