name: AEM Code Sync

on: 
 workflow_dispatch:
    
jobs:
  CodeSync:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Code Sync
        run: |
           sudo apt-get update && sudo apt-get install -y unzip git
           echo ${{ secrets.GIT_PAT }}
           echo ${{ secrets.GIT_User }}
           git remote add poc https://github.com/Vranda2088/AEM-Remote.git
           git config credential.username ${{ secrets.GIT_User }}
           git config credential.helper "!echo password=${{ secrets.GIT_PAT }}; echo"
           git checkout develop
           git pull 
           git push poc develop
           
        
