name: AEM Code Sync

on: 
 workflow_dispatch:
    
jobs:
  CodeSync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Code Sync
        run: |
           sudo apt-get install -y unzip git
           sudo git remote -v
           sudo git checkout origin/develop
#           git remote add poc https://github.com/Vranda2088/AEM-Remote.git
#           git config credential.username ${{ secrets.GIT_USER }}
#           git config credential.helper ${{ secrets.GIT_PAT }}
#           git pull 
#           git push poc develop
        shell: bash
           
        
