name: Trigger Deploy

#This workflow executes, whenever there is a pull request to develop branch.
# it will sync the code and trigger the pipeline in CM

on: 
 workflow_dispatch:
  inputs:
   env: 
    description: 'Environment Name'
    default: 'dev'
    type: environment

jobs:      
  Configure-IO:
    runs-on: ubuntu-latest
    steps:    
     - name: Checkout
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0
          
     - name: Setup Adobe CLI    
       uses: adobe/aio-cli-setup-action@1.1.0

     - name: Setup Adobe CLI  
       run: aio plugins:install @adobe/aio-cli-plugin-cloudmanager
     
     - name: Decrypt the json and key
       run: |
          chmod 775 * 
          cd config
          sh decrypt_secret.sh
       env:
          PK: ${{ secrets.PK }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          
     - name: Configure Authentication      
       run: |
         aio config:set ims.contexts.aio-cli-plugin-cloudmanager $HOME/secrets/config.json --file --json
         aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key $HOME/secrets/private.key --file    
         
  Deploy-Dev:
   if: ${{ github.event.inputs.env == 'dev' }}
   runs-on: ubuntu-latest
   environment: dev
   needs: Configure-IO
   steps:    

     - name: Trigger Dev Deploy
       run: echo This is trigger to dev pipeline

  Deploy-Main:
   if:  ${{ github.event.inputs.env == 'stage' }}
   runs-on: ubuntu-latest
   environment: stage
   needs: Configure-IO
   steps:    

     - name: Trigger Stage Deploy
       run: echo This is trigger to stage pipeline
