name: Dev Code Sync and Deploy

#This workflow executes, whenever there is a pull request to develop branch.
# it will sync the code and trigger the pipeline in CM

on:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:      
  Checkout-Sync-Dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:    
     - name: Checkout
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0
    
     - name: Code Sync to develop branch
       run: |
           sudo apt-get install -y unzip git
           git remote add poc https://github.com/Vranda1188/AEM-Remote.git
           git config credential.username ${{ secrets.GIT_USER }}
           git config credential.helper ${{ secrets.GIT_PAT }}
           git remote -v
           git checkout develop
           git pull
           git push -f -u poc develop
       shell: bash
  
  Configure-Adobe-IO:
    runs-on: ubuntu-latest
    needs: Checkout-Sync-Dev
    steps:
      - uses: adobe/aio-cli-setup-action@1.1.0
      - run: aio plugins:install @adobe/aio-cli-plugin-cloudmanager
      - run: |
          chmod 775 * 
          sh decrypt_secret.sh
          sh decrypt_key.sh
        env:
          PK: ${{ secrets.PK }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - run: |
         aio config:set ims.contexts.aio-cli-plugin-cloudmanager $HOME/secrets/config.json --file --json
         aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key $HOME/secrets/private.key --file
