name: Dev-CodeSync-PipelineTrigger

#This workflow executes, whenever there is a pull request to develop branch.
# it will sync the code and trigger the pipeline in CM

on: workflow_dispatch
#   pull_request:
#     branches: [develop]
#     types: [closed]

jobs:      
  Checkout-Sync-Dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:    
     - name: Checkout
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0
          
     - name: Setup Adobe CLI    
       uses: adobe/aio-cli-setup-action@1.1.0

     - name: Setup Adobe CLI  
       run: aio plugins:install @adobe/aio-cli-plugin-cloudmanager
     
     - name: Decrypt the json and key
       run: |
          chmod 775 * 
          sh decrypt_secret.sh
       env:
          PK: ${{ secrets.PK }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          
     - name: Configure Authentication      
       run: |
         aio config:set ims.contexts.aio-cli-plugin-cloudmanager $HOME/secrets/config.json --file --json
         aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key $HOME/secrets/private.key --file      
    
     - name: Code Sync to develop branch
       run: |
           sudo apt-get install -y unzip git
           git remote add poc https://github.com/Vranda1188/AEM-Remote.git
           git config credential.username ${{ secrets.GIT_USER }}
           git config credential.helper ${{ secrets.GIT_PAT }}
           git remote -v
           git checkout develop
           git pull
           git push -f -u poc develop
       shell: bash
  


