name: Dev Code Sync and Deploy

#This workflow executes, whenever there is a pull request to develop branch.
# it will sync the code and trigger the pipeline in CM

on:
  pull_request:
    branches:
     - develop
     - stage

jobs:      
  Checkout-Deploy-Dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:    
     - name: Checkout
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0
    
     - name: Code Sync to develop branch
       run: |
           sudo apt-get install -y unzip git
           git remote add poc https://github.com/Vranda1188/AEM-Remote.git
           git config credential.username ${{ secrets.GIT_USER }}
           git config credential.helper "!echo password=${{ secrets.GIT_PAT }}; echo"
           git remote -v
           git checkout develop
           git pull
           git push -f -u poc develop
       shell: bash
     
  Checkout-Stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:    
     - name: Checkout
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0
          
  Checkout-CodeSync-Stage:
    runs-on: ubuntu-latest
    environment: stage
    needs: Checkout-Stage
    steps:       
     - name: Code Sync to stage branch
       run: |
           sudo apt-get install -y unzip git
           git remote add poc https://github.com/Vranda1188/AEM-Remote.git
           git config credential.username ${{ secrets.GIT_USER }}
           git config credential.helper "!echo password=${{ secrets.GIT_PAT }}; echo"
           git remote -v
           git checkout stage
           git pull
           git push -f -u poc stage
       shell: bash
