name: Dev Stage Verification

on: workflow_dispatch

jobs:       
  Checkout:
    runs-on: ubuntu-latest
    environment: stage
    steps:    
     - name: Checkout
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GIT_PAT }}
    
     - name: Code Sync to Stage branch
       if: github.ref == 'refs/heads/stage'
       run: |
           sudo apt-get install -y unzip git
           sudo git remote add poc https://github.com/Vranda1188/AEM-Remote.git
           sudo git config credential.username ${{ secrets.GIT_USER }}
           sudo git config credential.helper ${{ secrets.GIT_PAT }}
           sudo git remote -v
           sudo git checkout stage
           sudo git pull
           sudo git push -f -u poc stage
       shell: bash


