name: Dev Code Sync and Deploy

#This workflow executes, whenever there is a pull request to develop branch.
# it will sync the code and trigger the pipeline in CM

on:
  pull_request:
    branches: [develop]

jobs:      
  Checkout-Deploy-Dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:    
     - name: Checkout
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GIT_PAT }}
    
     - name: Code Sync to develop branch
       run: |
           sudo apt-get install -y unzip git
           git remote add poc https://github.com/Vranda1188/AEM-Remote.git
           git config credential.username ${{ secrets.GIT_USER }}
           git config credential.helper ${{ secrets.GIT_PAT }}
           git remote -v
           git checkout develop
           git branch -r | grep -v '\->' | while read remote; do sudo git branch --track "#{remote#origin/}" "$remote"; done
           git fetch --all
           git pull --all
           git push -f -u poc develop
       shell: bash
