name: Develop Final Test

on: 
  workflow_dispatch
#   push:
#     branches: ['develop']

jobs:
  dev-sync:
    uses: ./.github/workflows/Final-Test.yml
    with:
      BRANCH: 'develop'
      ENVIRONMENT: dev
      VERIFICATION: www.google.com
    secrets: inherit
