# This is a basic workflow to help you get started with Actions
# It triggers on each push to the main branch and sets up AIO CLI using "AIO CLI Setup - Action" and then installs the plugin for cloud manager on top of the existing CLI.
name: Reusable Workflow Test

on: 
 workflow_dispatch:

jobs:
  Configure-Adobe-IO:
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.1.0
      
      - name: Install CM plugin
        run: aio plugins:install @adobe/aio-cli-plugin-cloudmanager
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Decrypt json
        run: |
          chmod 775 * 
          sh decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Decrypt Key
        run: |
          chmod 775 * 
          sh decrypt_key.sh
        env:
          PK: ${{ secrets.PK }}
          
      
      - name: Configure Authentication
        run: |
           aio config:set ims.contexts.aio-cli-plugin-cloudmanager $HOME/secrets/config.json --file --json
           aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key $HOME/secrets/private.key --file
           
           
