name: Main Final Test

on: 
  push:
    branches: ['main']

jobs:
  dev-sync:
    uses: ./.github/workflows/Final-Test.yml
    with:
      BRANCH: 'main'
      ENVIRONMENT: stage
      VERIFICATION: www.google.com
    secrets: inherit
