name: Stage Code Sync and Deploy

#This workflow executes, whenever there is a pull request to stage branch.
# it will sync the code and trigger the pipeline in CM once it is approved by the reviewer

on:
  pull_request:
    branches: [stage]

jobs:      
  Checkout-Stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:    
     - name: Checkout
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GIT_PAT }}
          
  Deploy-Stage:
    runs-on: ubuntu-latest
    needs: Checkout-Stage
    environment: stage  
    steps:    
     - name: Code Sync to Stage branch
       run: |
           sudo apt-get install -y unzip git
           sudo git remote add poc https://github.com/Vranda1188/AEM-Remote.git
           sudo git config credential.username ${{ secrets.GIT_USER }}
           sudo git config credential.helper ${{ secrets.GIT_PAT }}
           sudo git remote -v
           sudo git fetch --unshallow origin
           sudo git checkout stage
           sudo git pull
           sudo git push -f -u poc stage
       shell: bash
