# This is a basic workflow to help you get started with Actions
# It triggers on each push to the main branch and sets up AIO CLI using "AIO CLI Setup - Action" and then installs the plugin for cloud manager on top of the existing CLI.
name: AEM Conditional Checks

on: 
 workflow_dispatch:
  inputs:
   env:
    description: 'Env Name'
    default: 'dev'
    type: environment

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Job
        run: |
           echo You Selected ${{ github.event.inputs.env }}
           
  Dev:
    if: ${{ github.event.inputs.env == 'dev'}}
    runs-on: ubuntu-latest
    environment: dev
    needs: Test
    steps:
      - name: Configure Authentication
        run: |
           echo You Selected ${{ github.event.inputs.env }}

  Stage:
    if: ${{ github.event.inputs.env == 'stage'}}
    runs-on: ubuntu-latest
    environment: stage
    needs: Test
    steps:
      - name: Configure Authentication
        run: |
           echo You Selected ${{ github.event.inputs.env }}

  UAT:
    if: ${{ github.event.inputs.env == 'uat'}}
    runs-on: ubuntu-latest
    environment: uat
    needs: Test
    steps:
      - name: Configure Authentication
        run: |
           echo You Selected ${{ github.event.inputs.env }}
