# This is a basic workflow to help you get started with Actions

name: test Child trigger

# Controls when the workflow will run

on:
  workflow_run:
    workflows:
      - Dev Code Sync and Deploy
    types:
      - completed
 
jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
