name: HTTP Status Code

#This workflow executes, whenever there is a pull request to develop branch.
# it will sync the code and trigger the pipeline in CM

on: workflow_dispatch

jobs:      
  HTTP-Status-Code:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     
     - name: Check the status code and print it
       run: |
          response = $(curl -o /dev/null --silent --head --write-out '%{http_code}\n' "www.google.com" )
          echo "response from curl= $response"
          if: ${{ $response == '200' }}
          echo "It is a success response"
       shell: bash
