# This is a basic workflow to help you get started with Actions

name: Test Child trigger

# Controls when the workflow will run

on: 
 workflow_run:
   workflows:
      - Dev Code Sync and Deploy
   types:
      - completed
   branches:
      - stage
 
jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env
